[package]
authors = ["Andy Lok <andylokandy@hotmail.com>"]
edition = "2018"
name = "tikv-client"
version = "0.0.0"

[dependencies]
futures = "0.3"
lazy_static = "1"
pyo3 = { version = "0.14.4", features = ["abi3-py36", "extension-module"] }
tikv-client = { git = "https://github.com/andylokandy/client-rust.git", branch = "ssl" }
tokio = { version = "0.3", features = ["rt-multi-thread", "sync"] }

[lib]
crate-type = ["cdylib"]
name = "tikv_client"
